In [ ]:
# https://www.analyticsvidhya.com/blog/2021/12/stock-market-analysis-with-pandas-datareader-and-plotly-for-beginners/

In [12]:
import pandas as pd

In [1]:
from pandas_datareader import data as pdr
import yfinance as yf 
yf.pdr_override()

In [3]:
#Magnificient 7 stocks
tickers = ['AAPL', 'AMZN', 'GOOGL', 'META', 'MSFT', 'TSLA', 'NVDA']

In [4]:
df = pdr.DataReader(tickers, start='2020-01-01', end='2023-12-28', data_source='yahoo') #data_source='yahoo'
df.head()

[*********************100%***********************]  7 of 7 completed

            Adj Close                                                \
                 AAPL       AMZN      GOOGL        META        MSFT
Date
2020-01-02  73.152649  94.900497  68.433998  209.779999  154.779495
2020-01-03  72.441452  93.748497  68.075996  208.669998  152.852234
2020-01-06  73.018692  95.143997  69.890503  212.600006  153.247330
2020-01-07  72.675270  95.343002  69.755501  213.059998  151.850037
2020-01-08  73.844368  94.598503  70.251999  215.220001  154.268768

                                      Close                        ...  \
                 NVDA       TSLA       AAPL       AMZN      GOOGL  ...
Date                                                               ...
2020-01-02  59.744049  28.684000  75.087502  94.900497  68.433998  ...
2020-01-03  58.787785  29.534000  74.357498  93.748497  68.075996  ...
2020-01-06  59.034309  30.102667  74.949997  95.143997  69.890503  ...
2020-01-07  59.749023  31.270666  74.597504  95.343002  69.755501  ...
2020-01-08  59.861092  32.809334  75.797501  94.598503  70.251999  ...

                  Open                           Volume                      \
                  MSFT       NVDA       TSLA       AAPL      AMZN     GOOGL
Date
2020-01-02  158.779999  59.687500  28.299999  135480400  80580000  27278000
2020-01-03  158.320007  58.775002  29.366667  146322800  75288000  23408000
2020-01-06  157.080002  58.080002  29.364668  118387200  81236000  46768000
2020-01-07  159.320007  59.549999  30.760000  108872000  80898000  34330000
2020-01-08  158.929993  59.939999  31.580000  132079200  70160000  35314000


                META      MSFT      NVDA       TSLA
Date
2020-01-02  12077100  22622100  23753600  142981500
2020-01-03  11188400  21116200  20538400  266677500
2020-01-06  17058900  20813700  26263600  151995000
2020-01-07  14912400  21634100  31485600  268231500
2020-01-08  13475000  27746500  27710800  467164500

[5 rows x 42 columns]

In [20]:
# multi_data = yf.download(tickers, start='2020-01-01', end='2023-12-28', data_source='yahoo')
# multi_data.head()

In [9]:
start_date = '2020-01-01'
end_date = '2023-12-28'
source = 'yahoo'

In [16]:
dfs = [] 
for sym in tickers:
    df = pdr.DataReader(sym, start=start_date, end=end_date, data_source='yahoo')
    dfs.append(df)
#     print(f"DF for {sym} is :")
#     print(df)
    
combined_df = pd.concat(dfs, axis=1)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
                 Open       High        Low      Close  Adj Close     Volume  \
Date
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.152657  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  72.441460  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  73.018700  118387200
2020-01-07  74.959999  75.224998  74.370003  74.597504  72.675293  108872000
2020-01-08  74.290001  76.110001  74.290001  75.797501  73.844345  132079200

                 Open       High        Low      Close  ...        Low  \
Date                                                    ...
2020-01-02  93.750000  94.900497  93.207497  94.900497  ...  28.114000
2020-01-03  93.224998  94.309998  93.224998  93.748497  ...  29.128000
2020-01-06  93.000000  95.184502  93.000000  95.143997  ...  29.333332
2020-01-07  95.224998  95.694504  94.601997  95.343002  ...  30.224001
2020-01-08  94.902000  95.550003  94.321999  94.598503  ...  31.215334

                Close  Adj Close     Volume       Open       High        Low  \
Date
2020-01-02  28.684000  28.684000  142981500  59.687500  59.977501  59.180000
2020-01-03  29.534000  29.534000  266677500  58.775002  59.457500  58.525002
2020-01-06  30.102667  30.102667  151995000  58.080002  59.317501  57.817501
2020-01-07  31.270666  31.270666  268231500  59.549999  60.442501  59.097500
2020-01-08  32.809334  32.809334  467164500  59.939999  60.509998  59.537498

                Close  Adj Close    Volume
Date
2020-01-02  59.977501  59.744041  23753600
2020-01-03  59.017502  58.787785  20538400
2020-01-06  59.264999  59.034313  26263600
2020-01-07  59.982498  59.749020  31485600
2020-01-08  60.095001  59.861080  27710800

[5 rows x 42 columns]
(1004, 42)

In [19]:
print(combined_df.head(3))

                 Open       High        Low      Close  Adj Close     Volume  \
Date
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.152657  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  72.441460  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  73.018700  118387200

                 Open       High        Low      Close  ...        Low  \
Date                                                    ...
2020-01-02  93.750000  94.900497  93.207497  94.900497  ...  28.114000
2020-01-03  93.224998  94.309998  93.224998  93.748497  ...  29.128000
2020-01-06  93.000000  95.184502  93.000000  95.143997  ...  29.333332

                Close  Adj Close     Volume       Open       High        Low  \
Date
2020-01-02  28.684000  28.684000  142981500  59.687500  59.977501  59.180000
2020-01-03  29.534000  29.534000  266677500  58.775002  59.457500  58.525002
2020-01-06  30.102667  30.102667  151995000  58.080002  59.317501  57.817501

                Close  Adj Close    Volume
Date
2020-01-02  59.977501  59.744041  23753600
2020-01-03  59.017502  58.787785  20538400
2020-01-06  59.264999  59.034313  26263600

[3 rows x 42 columns]

In [17]:
print(combined_df.shape)

(1004, 42)

In [18]:
print(combined_df.columns)

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Open', 'High',
       'Low', 'Close', 'Adj Close', 'Volume', 'Open', 'High', 'Low', 'Close',
       'Adj Close', 'Volume', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Open',
       'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Open', 'High', 'Low',
       'Close', 'Adj Close', 'Volume'],
      dtype='object')

In [ ]:
#goog_df = pdr.DataReader(tickers, start=, end=, data_source='yahoo')

In [21]:
df_a = pdr.DataReader('AAPL', start='2020-01-01', end='2023-12-28', data_source='yahoo') #data_source='yahoo'
df_a.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close     Volume
Date
2020-01-02  74.059998  75.150002  73.797501  75.087502  73.152657  135480400
2020-01-03  74.287498  75.144997  74.125000  74.357498  72.441467  146322800
2020-01-06  73.447502  74.989998  73.187500  74.949997  73.018692  118387200
2020-01-07  74.959999  75.224998  74.370003  74.597504  72.675270  108872000
2020-01-08  74.290001  76.110001  74.290001  75.797501  73.844345  132079200

In [23]:
df.columns.names = ['Stock Info']
print(df.head(3))

Stock Info       Open       High        Low      Close  Adj Close    Volume
Date
2020-01-02  59.687500  59.977501  59.180000  59.977501  59.744041  23753600
2020-01-03  58.775002  59.457500  58.525002  59.017502  58.787785  20538400
2020-01-06  58.080002  59.317501  57.817501  59.264999  59.034313  26263600